[package]
name = "lwsfh"
version = "0.1.0"
edition = "2024"
description = "Libadoxon's window switcher for Hyprland - MacOs inspired window switcher"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
flume = "0.12"
freedesktop-icons = "0.4"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", version = "0.5.1" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", version = "0.5.1" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
  "font-kit",
  "wayland",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
